version: "3.8"

services:
    nginx:
        container_name: nginx
        networks:
            - inception
        depends_on:
            - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "443:443"
        restart: always
    mariadb:
        container_name: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        networks:
            - inception
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: on-failure
        expose:
            - "9000"

networks:
    inception:

volumes:
    mariadb:
    wordpress: