version: "3.8"

services:
    nginx:
        container_name: nginx
        networks:
            - inception
        depends_on:
            - wordpress
        image: nginx
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "443:443"
        restart: unless-stopped
    mariadb:
        container_name: mariadb
        networks:
            - inception
        image: mariadb
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        networks:
            - inception
        depends_on:
            - mariadb
        image: wordpress
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        expose:
            - "9000"

networks:
    inception:
        driver: bridge

volumes:
    mariadb:
    wordpress: